default_platform(:android)

platform :android do
  desc "Run unit tests and linting"
  lane :test do
    gradle(task: "test")
    gradle(task: "lint")
  end

  desc "Increment version code"
  lane :increment_version_code do
    android_set_version_code(gradle_file: "app/build.gradle")
  end

  desc "Set a specific version name (e.g., fastlane bump_version name:\"1.5.0\")"
  lane :bump_version do |options|
    android_set_version_name(
      version_name: options[:name],
      gradle_file: "app/build.gradle"
    )
  end

  desc "Build release AAB"
  lane :build do
    UI.message("***Make sure you have regenerated the data if necessary***")
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )
  end

  desc "Deploy to internal testing track"
  lane :internal do
    increment_version_code
    build
    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      changes_not_sent_for_review: true
    )
  end

  desc "Promote Internal to Alpha (Closed Testing)"
    lane :promote_to_alpha do
      upload_to_play_store(
        track: 'internal',
        track_promote_to: 'alpha',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_apk: true,
        skip_upload_changelogs: true
      )
  end

  desc "Promote Alpha to Beta (Open Testing @10%)"
  lane :promote_to_beta do
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'beta',
      rollout: '0.1' # Start with a 10% rollout
    )
  end

  desc "Deploy beta to Production @10%"
  lane :deploy do
    # This lane assumes you've already tested the build in Beta
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      rollout: '0.1' # Start with a 10% rollout
    )
  end

  desc "Deploy to alpha track"
  lane :alpha do
    increment_version_code
    build
    upload_to_play_store(
      track: "alpha",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to beta track"
  lane :beta do
    increment_version_code
    build
    upload_to_play_store(
      track: "beta",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to production"
  lane :production do
    increment_version_code
    build
    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Capture screenshots for Play Store. Specify --device_type=sevenInch for a tablet."
  lane :screenshots do
    gradle(
      task: "assembleDebug",
      project_dir: "./"
    )
    gradle(
      task: "assembleDebugAndroidTest",
      project_dir: "./"
    )
    screengrab
  end

  desc "Just upload the store metadata."
  lane :upload_metadata do |options|
      v_code = options[:version_code]
      upload_to_play_store(
        skip_upload_apk: true,
        skip_upload_aab: true,
        changes_not_sent_for_review: true,  # Acknowledges the draft state
        version_code: v_code,
        track: 'internal'
      )
  end
end
