import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import java.io.StringReader
import java.util.Properties

// The iOS app's Kotlin side (iOS port phase 4): the framework the Xcode app (ios/SkyMap) links,
// holding the app graph, the iOS platform edges — Core Motion, Core Location, the bundle — and
// the Compose Multiplatform UI root (D134). Everything below it is shared with Android.
plugins {
    id("skymap.ios-compose")
}

// The location sheet's map key, from the secrets file :app reads (app/no-checkin.properties, never
// checked in), as a constant in the framework, where Android has it as a resource. Without the
// file it is "unset", and the sheet leaves the map out.
val geoapifyKey: Provider<String> =
    providers
        .fileContents(rootProject.layout.projectDirectory.file("app/no-checkin.properties"))
        .asText
        .map { text ->
            Properties()
                .apply { load(StringReader(text)) }
                .getProperty("geoapify.api.key", "unset")
        }.orElse("unset")

val generateSecrets by tasks.registering {
    val key = geoapifyKey
    val output = layout.buildDirectory.dir("generated/secrets/kotlin")
    inputs.property("geoapifyKey", key)
    outputs.dir(output)
    doLast {
        // Checked rather than escaped: a key is letters, digits and dashes.
        require(key.get().all { it.isLetterOrDigit() || it == '-' || it == '_' }) {
            "geoapify.api.key has unexpected characters"
        }
        output.get().file("com/google/android/stardroid/ios/Secrets.kt").asFile.apply {
            parentFile.mkdirs()
            writeText(
                "// Generated by :app-ios:generateSecrets from app/no-checkin.properties.\n" +
                    "package com.google.android.stardroid.ios\n\n" +
                    "internal const val GEOAPIFY_MAPS_API_KEY = \"${key.get()}\"\n",
            )
        }
    }
}

kotlin {
    targets.withType<KotlinNativeTarget>().configureEach {
        binaries.framework {
            baseName = "SkyMapKit"
            isStatic = true
        }
    }
    sourceSets {
        iosMain {
            kotlin.srcDir(generateSecrets)
        }
        iosMain.dependencies {
            implementation(project(":shared:viewmodels"))
            implementation(project(":shared:ui"))
            implementation(project(":shared:layers"))
            implementation(project(":shared:model"))
            implementation(project(":data"))
            implementation(project(":render:metal"))
            implementation(libs.cmp.runtime)
            implementation(libs.cmp.foundation)
            implementation(libs.cmp.ui)
            implementation(libs.cmp.material3)
        }
    }
}
