import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest
import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest

plugins {
    id("skymap.ios-library")
}

// The Metal SkyRenderer backend (D128): Kotlin/Native calling Metal directly. The shaders are
// real .metal files under shaders/, embedded as one Kotlin string and compiled at runtime by
// MTLDevice.newLibraryWithSource — the way :render:gles3 compiles its GLSL — so nothing here
// needs Xcode's offline Metal toolchain.

/**
 * Concatenates shaders/ into `MetalShaderSource.SOURCE`: common.metal first (the shared uniforms
 * and helpers every other file uses), then the rest in name order, so the output is stable.
 */
abstract class EmbedMetalShaders : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val shaderDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun embed() {
        val files =
            shaderDir.get().asFile.listFiles { f -> f.extension == "metal" }!!
                .sortedWith(compareBy({ it.name != "common.metal" }, { it.name }))
        val source = files.joinToString("\n") { "// ---- ${it.name}\n${it.readText()}" }
        require("\"\"\"" !in source && "$" !in source) {
            "Metal source contains a sequence a Kotlin raw string cannot hold"
        }
        val out = outputDir.get().asFile.resolve("com/google/android/stardroid/render/metal")
        out.mkdirs()
        // Plain concatenation, not trimMargin: that would also strip a shader line's leading `|`.
        val quotes = "\"\"\""
        out.resolve("MetalShaderSource.kt").writeText(
            "// Generated by :render:metal:embedMetalShaders from shaders/*.metal. Do not edit.\n" +
                "package com.google.android.stardroid.render.metal\n\n" +
                "internal object MetalShaderSource {\n" +
                "    const val SOURCE: String = $quotes\n" +
                source +
                "\n$quotes\n}\n",
        )
    }
}

val embedMetalShaders =
    tasks.register<EmbedMetalShaders>("embedMetalShaders") {
        shaderDir.set(layout.projectDirectory.dir("shaders"))
        outputDir.set(layout.buildDirectory.dir("generated/metalShaders"))
    }

kotlin {
    sourceSets {
        iosMain {
            kotlin.srcDir(embedMetalShaders)
            dependencies {
                api(project(":render:api"))
            }
        }
        commonTest.dependencies {
            implementation(project(":render:testscene"))
        }
    }
}

// The render tests write what they drew as PNGs here, for eyeballing. xcrun simctl forwards only
// SIMCTL_CHILD_-prefixed variables into the simulated process.
tasks.withType<KotlinNativeTest>().configureEach {
    val out = layout.buildDirectory.dir("reports/metal-renders").get().asFile
    outputs.dir(out).withPropertyName("renders")
    environment("SIMCTL_CHILD_SKYMAP_RENDER_OUT", out.absolutePath)
}

// The render tests need the simulator's GPU. Kotlin runs simulator tests with
// `simctl spawn --standalone`, which skips the booted device's services — Metal among them — so
// MTLCreateSystemDefaultDevice() returns nil. These tests instead run on a booted simulator,
// booting it first if it is not already up (booting is idempotent; a running one stays running).
tasks.withType<KotlinNativeSimulatorTest>().configureEach {
    standalone.set(false)
    val simulator = device
    doFirst {
        val udid = simulator.get()
        ProcessBuilder("xcrun", "simctl", "boot", udid).redirectErrorStream(true).start().waitFor()
        val booted =
            ProcessBuilder("xcrun", "simctl", "bootstatus", udid, "-b")
                .redirectErrorStream(true)
                .start()
                .waitFor()
        check(booted == 0) { "simulator $udid did not boot" }
    }
}

// The generated source is not ours to lint.
ktlint {
    filter {
        exclude { it.file.path.contains("/generated/") }
    }
}
